### ISSUE TITLE
Scrapping multiple websites in a single script

### ISSUE THREAD

**Issue by matifayaz** [enjoys-sashimi/contact-scraper#1]
Hi,
Can we scrape multiple websites in a single script? When I tried it I get **twisted.internet.error.ReactorNotRestartable**

Thanks

**Comment by smcn20** [comment]
Hi
Did you ever get this resolved? I have the same query

**Comment by smcn20** [comment]
Hi, I am also experiencing issues when using this code for multiple URLs (however I haven't been experiencing the error @matifayaz has mentioned.) 
When multiple URLs are listed in the example.py file, for example:
`instance` = Controller(starting_urls=['https://www.python.org/', 'https://www.example.com', 'https://www.example2.com'],
            scrape_numbers=False,
            scrape_emails=True,
            region="US",
            max_results=2)``

I have the scrape_numbers boolean set to False as I don't wish to see this data.
The output.json file will only show a maximum of 2 email addresses. It only shows the last two email addresses scraped (from https://www.example2.com) and appears to overwrite the previously scraped email addresses from the preceding URLs.

This is my first post and I'm totally new to coding so I'd appreciate some advice and apologies if anything above isn't as clear as it should be

**Comment by pushpam5** [comment]
> Hi, I am also experiencing issues when using this code for multiple URLs (however I haven't been experiencing the error @matifayaz has mentioned.)
> When multiple URLs are listed in the example.py file, for example:
> `instance` = Controller(starting_urls=['https://www.python.org/', 'https://www.example.com', 'https://www.example2.com'],
> scrape_numbers=False,
> scrape_emails=True,
> region="US",
> max_results=2)``
> 
> I have the scrape_numbers boolean set to False as I don't wish to see this data.
> The output.json file will only show a maximum of 2 email addresses. It only shows the last two email addresses scraped (from https://www.example2.com) and appears to overwrite the previously scraped email addresses from the preceding URLs.
> 
> This is my first post and I'm totally new to coding so I'd appreciate some advice and apologies if anything above isn't as clear as it should be

You need to change the max_results parameter from 2 to the number of records you want.

**Comment by kring317** [comment]
I am also facing the same issue, I have tried appending the data in json by changing 'r' to 'a' in:
with open('output.json', 'r') as raw_output:
    data = raw_output.read()
    output = json.update(data)

But nothing works, request immediate support- need it college assignment..

**Comment by enjoys-sashimi** [comment]
> But nothing works

I'm sorry to hear that, I just tested this repo from scratch in Windows and Ubuntu; no issues on my end, so please ensure that you are properly setting up the environment and python. 

Unfortunately I cannot commit code to this repository, or any open-source repository due to my job. I will update the README to reflect that this is no longer a supported repo, apologies.

**Comment by pushpam5** [comment]
> I am also facing the same issue, I have tried appending the data in json by changing 'r' to 'a' in:
> with open('output.json', 'r') as raw_output:
> data = raw_output.read()
> output = json.update(data)
> 
> But nothing works, request immediate support if possible, please- need it for a college assignment..

Please look into following repo : 
https://github.com/pushpam5/Email-PhoneNo.Scrapper
 The code is not so clean but will help in solving your problem.Feel free to contact for any further clarifications.

**Comment by kring317** [comment]
Thanks @enjoys-sashimi, were you able to scrape details from multiple URLs? Like adding ['https://www.python.org/', 'https://www.example.com', 'https://www.example2.com']

When I try to scrape it, the output json file shows only 1 entry from the last website, I guess it overwrites all the previous entries, would request you to run the query with 3-4 websites and check the output json once. 

And yeah, thanks a lot for sharing this code here, this is just amazing! :)

**Comment by ShortMan443** [comment]
Yeah, the same thing as the post above. I'm only getting the last data.

**Comment by enjoys-sashimi** [comment]
>  were you able to scrape details from multiple URLs? Like adding ['https://www.python.org/', 'https://www.example.com', 'https://www.example2.com']


Ah, yup I see the problem, there's a multitude of solutions! Many of which can be implemented with a single line of code. 

It would be great if somebody made their own implementation and created a pull request, it would help others :) 

- - -
### Issue
Take a look at [contactscraper/pipelines.py](https://github.com/enjoys-sashimi/contact-scraper/blob/master/contactscraper/pipelines.py#L11-L18) it handles parsing raw text from websites & **writing output to disk**. 

```
class ContactscraperPipeline:
    def open_spider(self, spider):
        self.file = open('output.json', 'w')
        ...
        ..
        .
```

#### Issue
The above `open_spider(self, spider)` method is called once for each `url` in [`Controller(starting_url)`](https://github.com/enjoys-sashimi/contact-scraper/blob/master/contactscraper/controller/controller.py#L69-L76). 

The output filename is static, this means the current URL rewrites the output generated by the previous.
#### Possible fix
The string `'output.json'` should be dynamic (unique) for every call to`open_spider(self, spider)`. This means the naive solution can be boiled down to simply _generating a unique string_.

Slightly more effort and you could make this output name something perhaps, as well. 

cheers

**Comment by kring317** [comment]
Thank you @enjoys-sashimi! Unfortunately, I don't know about coding much, won't be able to use the fix :(

Can someone please add the fix and update it?

**Comment by solo-fish** [comment]
> Thank you @enjoys-sashimi! Unfortunately, I don't know about coding much, won't be able to use the fix :(

Check out these [One liners for random strings](https://gist.github.com/henriquemenezes/c259b3b24b9fc96a1af8)

my dude you can do it, I believe in ya.

**Comment by kring317** [comment]
Thank you solo-fish for your confidence in me, I tried to connect the dots and add the fix- but couldn't do it. 

Need real help with adding the fix, can you please help me with that?

**Comment by enjoys-sashimi** [comment]
> Need real help with adding the fix, can you please help me with that?

I hope I can - could you provide more detail in what you're confused about or what specifically is not working?

**Comment by kring317** [comment]
In contactscraper/pipelines.py, how do I generate a unique string, I tried multiple solutions, one of them being changing "self.file = open('output.json', 'w')" to "self.file = open('output.json', '**_a_**')" to append the data. But it doesn't work as well. What exact change can I make in the code to make it run?

**Comment by kring317** [comment]
Hi @enjoys-sashimi, did you get a chance to check my query?

**Comment by enjoys-sashimi** [comment]
@kring317 @ShortMan443 @smcn20 @matifayaz 

Somebody has raised a fix to this issue! You can all thank @doodles526
