### ISSUE TITLE
Dynamic output file-name

### ISSUE THREAD

**Issue by matifayaz** [enjoys-sashimi/contact-scraper#2]
Hi,
Currently the scrapper generates output file with fixed name: **output.json**. Can we input the output file-name when we initiate the scrapper? 

Thanks

**Comment by enjoys-sashimi** [comment]
Hi this is a good idea and would be a simple change.

Unfortunately I cannot commit code to this repository, or any open-source repository due to my job. I will update the README to reflect that this is no longer a supported repo, apologies.

**Comment by shashaa35** [comment]
I have forked this and implemented this feature. You can have a look : https://github.com/shashaa35/contact-scraper

**Comment by enjoys-sashimi** [comment]
Thanks @shashaa35 - next time raise a PR like @doodles526 

issue closed with #1
